[alignmenttrees]
alignment = /public/home/chenghj/YS/ancestral_karyotype/wgdi_for_tree/modified_sporbolus_genus_tree/merged.alignment.csv
gff = /public/home/chenghj/reference_for_wgdi/rawfile_gff3_fa_map/Eragrostis_tef_chr_subgenomeA.gff
lens = Eragrostis_tef_chr_subgenomeA.4.len
dir = Eragrostis_tef_chr_subgenomeA.4.tree
sequence_file = /public/home/chenghj/YS/ancestral_karyotype/wgdi_for_tree/modified_sporbolus_genus_tree/all.prot.fa
trees_file =  Eragrostis_tef_chr_subgenomeA.4.trees.nwk
align_software = mafft
tree_software = iqtree
model = MFP
trimming = trimal
minimum = 6
delete_detail = true
